name: C++ CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Две разные ОС
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Важно для получения тегов!
    
    - name: Get version from tag
      id: get_version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          # Если это тег: v1.0.0 → 1.0.0
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "Using tag version: $VERSION"
        else
          # Если обычный коммит
          VERSION="1.0.0-dev"
          echo "Using dev version: $VERSION"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Setup CMake
      uses: actions/.github-workflows-@v2
    
    - name: Configure CMake
      run: cmake -B build -S . -DVERSION_PROJECT="$VERSION"
    
    - name: Build project
      run: cmake --build build
    
    - name: Run program
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          ./build/Release/hello_world.exe
        else
          ./build/hello_world
        fi
